### ISSUE TITLE
How to check out books with out patron login?

### ISSUE THREAD

**Issue by daltonfury42** [tzeumer/SIP2-Client-for-Python#2]
Hi @tzeumer,

I am trying to write a very basic app for a RFID kiosk. The kiosk will read the RFID enabled patron card, and this will serve as an authentication.

So is it possible to perform a check out to the patron's account without asking the patron to enter his password?

Regards,

**Comment by tzeumer** [comment]
Hi again @daltonfury42 

Yes, it's absolutely possible if you got a SIP2 server (it wasn't possible with SIP1). It's a different message id though (63/64 instead of 23/24; you can check it here: http://multimedia.3m.com/mws/media/355361O/sip2-protocol.pdf). The Helmut-Schmidt University library (Germany/Hamburg) did exactly that (RFID library cards for login without password). Probably interesting stuff for you from the admin over there: https://github.com/GallusMax?tab=repositories

I changed the default in the SIP" client from 23/24 to 63/64 with this [this](https://github.com/tzeumer/SIP2-Client-for-Python/commit/c1bfe3af891b94e3f50a58f617711cedcdf1cb4e) commit that I pushed a few hours ago. 

Now you just have to leave password empty. Even though this should be enough by the SIP2 protocol definition, your probably have to configure your server to really allow this
